# Generated by Django 5.1.2 on 2024-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_tickets_quanlity_alter_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
