# Generated by Django 5.1.2 on 2024-10-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
