# Generated by Django 5.1.2 on 2024-10-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.ImageField(default=None, upload_to='images/%Y/%m'),
        ),
    ]
