# Generated by Django 5.1.2 on 2024-10-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_alter_tour_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
