# Generated by Django 5.1.2 on 2024-10-26 13:47

import Management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_alter_tour_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='user_tour',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='images',
            field=models.ImageField(default=None, upload_to=Management.models.user_directory_path),
        ),
    ]
