# Generated by Django 5.1.2 on 2024-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_tour_user_tour_alter_tour_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='remaining_seats',
            field=models.IntegerField(null=True),
        ),
    ]
