# Generated by Django 5.1.2 on 2024-10-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_remove_tour_images_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
