# Generated by Django 5.1.2 on 2024-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0011_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_state',
            field=models.CharField(choices=[('successful', 'Successful'), ('unpaid', 'Unpaid')], default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash'), ('credit-card', 'Credit-card'), ('e-wallet', 'E-wallet')], default='cash', max_length=15),
        ),
    ]
