# Generated by Django 5.1.2 on 2024-10-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_payment_payment_state_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
