# Generated by Django 5.1.2 on 2024-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_alter_images_tour_alter_tour_price'),
        ('Management', '0013_rename_quanlity_tickets_quantity'),
    ]

    operations = [
    ]
