# Generated by Django 5.1.2 on 2024-11-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_merge_20241031_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='user_tour',
        ),
        migrations.AlterField(
            model_name='images',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=500),
        ),
    ]
