# Generated by Django 5.1.2 on 2024-11-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0015_remove_tour_user_tour_alter_images_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(),
        ),
    ]
