# Generated by Django 5.1.2 on 2024-11-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0016_alter_tour_description_alter_tour_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='booked', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash'), ('credit-card', 'Credit-card'), ('e-wallet', 'E-wallet')], default='cash', max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_state',
            field=models.CharField(choices=[('successful', 'Successful'), ('unpaid', 'Unpaid')], default='unpaid', max_length=200),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='quantity',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_code',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
