# Generated by Django 5.1.2 on 2024-11-03 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0017_alter_booking_status_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash'), ('credit-card', 'Credit-card'), ('e-wallet', 'E-wallet')], default='cash', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_state',
            field=models.CharField(choices=[('successful', 'Successful'), ('unpaid', 'Unpaid')], default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.users')),
            ],
        ),
    ]
