# Generated by Django 5.1.2 on 2024-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0019_alter_payment_amount_alter_tickets_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('admin', 'Admin')], default='customer', max_length=100),
        ),
    ]
