# Generated by Django 5.1.2 on 2024-11-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0021_remove_booking_payment_method_tickets_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.booking'),
        ),
    ]
