# Generated by Django 5.1.2 on 2024-11-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0023_alter_payment_booking_alter_tickets_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
