# Generated by Django 5.1.2 on 2024-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0025_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
