# Generated by Django 5.1.2 on 2024-11-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0024_alter_booking_booking_date'),
        ('Management', '0028_alter_booking_booking_date_and_more'),
    ]

    operations = [
    ]
