# Generated by Django 5.1.2 on 2024-11-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0029_merge_20241110_2314'),
        ('Management', '0029_merge_20241111_0147'),
    ]

    operations = [
    ]
