# Generated by Django 5.1.2 on 2024-11-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0030_merge_20241111_0744'),
        ('Management', '0030_merge_20241111_0808'),
    ]

    operations = [
    ]
