# Generated by Django 5.1.2 on 2024-11-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0031_merge_20241111_0941'),
        ('Management', '0031_merge_20241111_0946'),
        ('Management', '0031_merge_20241111_0947'),
    ]

    operations = [
    ]
